In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("../res2.xlsx")
df.head()

,org,repo,full_name,private,archived,fork,fork_source,is_generated_from_template,template_source,pushed_at,...,code_scanning_alerts,default_branch_protected,protection_settings,community,community_health,community_files,has_security_policy,has_code_of_conduct,flags,branch_protection_access
0,ministryofjustice,hmpps-adjustments-api,ministryofjustice/hmpps-adjustments-api,False,False,False,NaN,False,NaN,2026-03-05T12:35:16Z,...,NaN,1.0,['required_status_checks'],"{'health_percentage': 75, 'description': 'API ...",75.0,"code_of_conduct, code_of_conduct_file, contrib...",False,True,NaN,NaN
1,ministryofjustice,hmpps-community-payback-ui,ministryofjustice/hmpps-community-payback-ui,False,False,False,NaN,False,NaN,2026-03-05T12:35:13Z,...,NaN,1.0,['required_status_checks'],"{'health_percentage': 100, 'description': 'UI ...",100.0,"code_of_conduct, code_of_conduct_file, contrib...",False,True,NaN,NaN
2,ministryofjustice,opg-lpa,ministryofjustice/opg-lpa,False,False,False,NaN,False,NaN,2026-03-05T12:35:04Z,...,NaN,1.0,['required_status_checks'],"{'health_percentage': 87, 'description': 'The ...",87.0,"code_of_conduct, code_of_conduct_file, contrib...",False,True,NaN,NaN
3,ministryofjustice,opg-digideps,ministryofjustice/opg-digideps,False,False,False,NaN,False,NaN,2026-03-05T12:34:32Z,...,NaN,1.0,[],"{'health_percentage': 87, 'description': 'Digi...",87.0,"code_of_conduct, code_of_conduct_file, contrib...",False,True,NaN,NaN
4,ministryofjustice,hmpps-digital-prison-services,ministryofjustice/hmpps-digital-prison-services,False,False,False,NaN,False,NaN,2026-03-05T12:34:12Z,...,NaN,1.0,['required_status_checks'],"{'health_percentage': 87, 'description': 'HMPP...",87.0,"code_of_conduct, code_of_conduct_file, contrib...",False,True,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   org                         800 non-null    str
 1   repo                        800 non-null    str
 2   full_name                   800 non-null    str
 3   private                     800 non-null    bool
 4   archived                    800 non-null    bool
 5   fork                        800 non-null    bool
 6   fork_source                 8 non-null      str
 7   is_generated_from_template  800 non-null    bool
 8   template_source             4 non-null      str
 9   pushed_at                   800 non-null    str
 10  default_branch              800 non-null    str
 11  language                    780 non-null    str
 12  open_issues                 800 non-null    int64
 13  stargazers                  800 non-null    int64
 14  workflows_count             800 non-null    int64
 15  workflows                   800 non-null    str
 16  workflows_names             628 non-null    str
 17  secret_scanning_access      800 non-null    str
 18  secret_scanning_alerts      643 non-null    float64
 19  dependabot_access           800 non-null    str
 20  dependabot_alerts           70 non-null     float64
 21  code_scanning_access        800 non-null    str
 22  code_scanning_alerts        70 non-null     float64
 23  default_branch_protected    642 non-null    float64
 24  protection_settings         642 non-null    str
 25  community                   800 non-null    str
 26  community_health            637 non-null    float64
 27  community_files             637 non-null    str
 28  has_security_policy         800 non-null    bool
 29  has_code_of_conduct         800 non-null    bool
 30  flags                       163 non-null    str
 31  branch_protection_access    158 non-null    str
dtypes: bool(6), float64(5), int64(3), str(18)
memory usage: 167.3 KB

In [5]:
df["language"].value_counts(dropna=False)

language
TypeScript          138
Kotlin              127
HCL                 100
Python               92
Java                 54
HTML                 50
JavaScript           39
Ruby                 36
Go                   26
Shell                24
NaN                  20
Dockerfile           15
PHP                  14
C#                   12
R                     9
PLSQL                 7
Nunjucks              6
Makefile              5
Gherkin               3
CSS                   3
PowerShell            2
Jupyter Notebook      2
PLpgSQL               2
Go Template           2
Smarty                2
Lua                   1
Mermaid               1
Rich Text Format      1
CoffeeScript          1
VBScript              1
YAML                  1
C                     1
Rust                  1
Mustache              1
XSLT                  1
Name: count, dtype: int64

In [13]:
df[["private","archived","fork","is_generated_from_template"]].apply(lambda s: s.value_counts(dropna=False))

       private  archived  fork  is_generated_from_template
False      625       799   792                         796
True       175         1     8                           4

In [14]:
df['template_source'].value_counts()

template_source
ministryofjustice/template-repository    4
Name: count, dtype: int64

In [15]:
df['fork_source'].value_counts()

fork_source
hugerte/hugerte-angular                                          1
ministryofjustice/terraform-aws-observability-platform-tenant    1
ministryofjustice/coat-cur-data-pipeline                         1
joelanman/govuk-prototype-kit-prototype                          1
oracle/docker-images                                             1
ministryofjustice/hmpps-template-kotlin                          1
zalando/tech-radar                                               1
cartalyst/sentinel                                               1
Name: count, dtype: int64

In [16]:
df[["dependabot_access","code_scanning_access","code_scanning_access"]].apply(lambda s: s.value_counts(dropna=False))

           dependabot_access  code_scanning_access  code_scanning_access
forbidden              730.0                   730                   730
not_found                NaN                    12                    12
ok                      70.0                    58                    58

In [9]:
df['pushed_at'].describe()

count                      800
unique                     797
top       2026-03-05T12:21:59Z
freq                         2
Name: pushed_at, dtype: object

In [18]:
# Parse ISO-8601 strings like '2026-03-05T12:35:16Z' into timezone-aware datetimes (UTC)
df["pushed_at_dt"] = pd.to_datetime(df["pushed_at"], utc=True, errors="coerce")

# "Age" since pushed_at (relative to now)
now_utc = pd.Timestamp.now(tz="UTC")
df["age"] = now_utc - df["pushed_at_dt"]  # timedelta64[ns]

# Handy numeric version of age for stats/plots
df["age_days"] = df["age"] / pd.Timedelta(days=1)

# Quick stats
print("pushed_at range:", df["pushed_at_dt"].min(), "->", df["pushed_at_dt"].max())
print("avg age:", df["age"].mean())
print("avg age (days):", df["age_days"].mean())

# Optional: distribution of events by day
by_day = df["pushed_at_dt"].dt.floor("D").value_counts().sort_index()
display(by_day)

pushed_at range: 2026-02-24 03:03:47+00:00 -> 2026-03-05 12:35:16+00:00
avg age: 1 days 21:03:49.004045
avg age (days): 1.8661250137615744

pushed_at_dt
2026-02-24 00:00:00+00:00     15
2026-02-25 00:00:00+00:00     34
2026-02-26 00:00:00+00:00     24
2026-02-27 00:00:00+00:00     17
2026-02-28 00:00:00+00:00     14
2026-03-01 00:00:00+00:00     40
2026-03-02 00:00:00+00:00     83
2026-03-03 00:00:00+00:00     63
2026-03-04 00:00:00+00:00    190
2026-03-05 00:00:00+00:00    320
Name: count, dtype: int64

In [23]:
df['workflows_names'].value_counts()

workflows_names
Deploy to environment, Pipeline [test -> build -> deploy], Security CodeQL actions scan, Security OWASP dependency check, Security trivy dependency check, Security veracode pipeline scan, Security veracode policy scan                                                   27
Deploy to environment, Pipeline [test -> build -> deploy], Security CodeQL actions scan, Security npm dependency check, Security trivy dependency check, Security veracode pipeline scan, Security veracode policy scan, Dependabot Updates                                 22
Secure Code Analysis, Generate Terraform README docs, Format Code: ensure code formatting guidelines are met, .github/workflows/go-terratest.yml, Scorecards supply-chain security, Terraform Static Code Analysis, Dependabot Updates, Dependency Graph                    16
Dependabot Updates                                                                                                                                                                                                                                                          11
Dependency Review, Dependabot Updates                                                                                                                                                                                                                                       10
                                                                                                                                                                                                                                                                            ..
Test & Build, Create Tag, Generate Scan Report, Pact Provider Verification, Dependency Graph                                                                                                                                                                                 1
.github/workflows/build-multi-platform-image.yml, Test & Build, Create Tag, Generate Scan Report                                                                                                                                                                             1
Test & Build, Create Tag, Generate Scan Report, Dependency Graph                                                                                                                                                                                                             1
Build and Deploy Test Env, Deploy to environment, Pipeline [test -> build -> deploy], Security CodeQL actions scan, Security OWASP dependency check, Security trivy dependency check, Security veracode pipeline scan, Security veracode policy scan, Dependabot Updates     1
Clean ECR, Dependabot Updates, CodeQL                                                                                                                                                                                                                                        1
Name: count, Length: 458, dtype: int64